"""Dynamic staging DAGs for declarative sources.

The DAGs generated here share the same operational flow:

    source file
      |-(extract_to_raw)-> lakehouse/raw/<source>/ingest_date=YYYY-MM-DD
          |-(transform_to_staging)-> lakehouse/staging/<source>/ingest_date=YYYY-MM-DD

PySpark logic lives in ``pipelines/staging_pipeline.py`` and each table
contract lives in ``pipelines/<source>/staging_<source>.json``.
"""
from __future__ import annotations

import logging

import pendulum
from airflow.exceptions import AirflowSkipException
from airflow.sdk import Asset, dag, task

from connections.spark_session import run_spark
from scripts.general.utils import (
    partition_path,
    partition_processed,
    resolve_ingest_date,
)
from staging_pipeline import (
    active_sources,
    extract_to_raw,
    get_source_config,
    raw_dir_for,
    staging_dir_for,
    transform_to_staging,
)

log = logging.getLogger(__name__)

DEFAULT_ARGS = {
    "owner": "data-eng",
    "retries": 2,
    "retry_delay": pendulum.duration(minutes=1),
}


def _doc_for(source: str) -> str:
    """Build the DAG documentation for a staging source."""
    return f"""DAG ``{source}`` - generic staging ingestion.

Flow across the lakehouse layers, partitioned by ingestion date::

    configured source input
      |-(extract_to_raw)-> lakehouse/raw/{source}/ingest_date=YYYY-MM-DD
          |-(transform_to_staging)-> lakehouse/staging/{source}/ingest_date=YYYY-MM-DD

The DAG is generated by ``airflow/dags/staging_sources.py``. Shared
PySpark logic lives in ``pipelines/staging_pipeline.py`` and the source
contract lives in ``pipelines/{source}/staging_{source}.json``.

Each run writes to its own ``ingest_date`` partition. Reprocessing the
same date only overwrites that partition.

Before doing work, each task checks whether its target partition already
has a ``_SUCCESS`` marker. If it exists, the task is skipped instead of
reprocessing.
"""


def build_staging_dag(source: str):
    """Create one staging DAG for a registered declarative source."""
    source_config = get_source_config(source)
    staging_asset = Asset(f"staging_{source}")
    raw_base_dir = raw_dir_for(source)
    staging_base_dir = staging_dir_for(source)

    @dag(
        dag_id=source,
        description=source_config["description"],
        schedule="*/10 * * * *",
        start_date=pendulum.datetime(2024, 1, 1, tz="UTC"),
        catchup=False,
        max_active_runs=1,
        default_args=DEFAULT_ARGS,
        tags=["bigcore", source, "staging"],
        doc_md=_doc_for(source),
    )
    def staging_source_dag():
        @task(task_id="extract_to_raw")
        def extract_to_raw_task(**context) -> dict:
            """Read the source input and write the raw partition."""
            ingest_date = resolve_ingest_date(context)
            destination = partition_path(raw_base_dir, ingest_date)

            if partition_processed(destination):
                log.info(
                    "Raw for %s already processed (%s) - skipping extraction",
                    ingest_date,
                    destination,
                )
                raise AirflowSkipException(f"raw ingest_date={ingest_date} already exists")

            metrics = run_spark(f"{source}_extract", extract_to_raw, source, ingest_date)
            log.info("Raw layer written for %s: %s", source, metrics)
            return metrics

        @task(
            task_id="transform_to_staging",
            outlets=[staging_asset],
            trigger_rule="none_failed",
        )
        def transform_to_staging_task(**context) -> dict:
            """Read raw, apply the table config and write staging."""
            ingest_date = resolve_ingest_date(context)
            destination = partition_path(staging_base_dir, ingest_date)

            if partition_processed(destination):
                log.info(
                    "Staging for %s already processed (%s) - skipping transform",
                    ingest_date,
                    destination,
                )
                raise AirflowSkipException(f"staging ingest_date={ingest_date} already exists")

            metrics = run_spark(f"{source}_transform", transform_to_staging, source, ingest_date)
            log.info(
                "Staging layer written for %s: %s records (%s flagged for quality)",
                source,
                metrics["records_out"],
                metrics["records_flagged"],
            )
            return metrics

        extract_to_raw_task() >> transform_to_staging_task()

    return staging_source_dag()


for source_name in active_sources():
    globals()[source_name] = build_staging_dag(source_name)
