"""Dynamic staging DAGs for declarative sources.

The DAGs generated here share the same operational flow:

    source file
      |-(extract_to_raw)-> lakehouse/raw/<source>/ingest_date=YYYY-MM-DD
          |-(transform_to_staging)-> lakehouse/staging/<source>/ingest_date=YYYY-MM-DD
              |                      (quality_ok rows only; rejected rows go to
              |                       lakehouse/quarantine/<source>/ingest_date=YYYY-MM-DD)
              |-(data_quality)-> log alert with the quarantined count, reasons
                                 and percentage over the partition total

PySpark logic lives in ``pipelines/staging_pipeline.py`` and each table
contract lives in ``pipelines/<source>/staging_<source>.json``.
"""
from __future__ import annotations

import logging

import pendulum
from airflow.exceptions import AirflowSkipException
from airflow.sdk import Asset, dag, task
from staging_pipeline import (
    active_sources,
    extract_to_raw,
    get_source_config,
    raw_dir_for,
    report_data_quality,
    staging_dir_for,
    transform_to_staging,
)

from connections.spark_session import run_spark
from scripts.general.delta_io import delta_partition_processed
from scripts.general.utils import resolve_ingest_date

log = logging.getLogger(__name__)

TASK_RETRIES = 2
RETRY_DELAY = pendulum.duration(minutes=1)
# Cadence at which every staging source is polled for new data.
STAGING_SCHEDULE = "*/10 * * * *"

DEFAULT_ARGS = {
    "owner": "data-eng",
    "retries": TASK_RETRIES,
    "retry_delay": RETRY_DELAY,
}


def _doc_for(source: str) -> str:
    """Build the DAG documentation for a staging source."""
    return f"""DAG ``{source}`` - generic staging ingestion.

Flow across the lakehouse layers, partitioned by ingestion date::

    configured source input
      |-(extract_to_raw)-> lakehouse/raw/{source}/ingest_date=YYYY-MM-DD
          |-(transform_to_staging)-> lakehouse/staging/{source}/ingest_date=YYYY-MM-DD
              |-(data_quality)-> log alert for the quarantined records

Only rows with ``quality_ok`` True reach staging; rejected rows are
written to ``lakehouse/quarantine/{source}/`` and the ``data_quality``
task reports their count, reasons and percentage over the total.

The DAG is generated by ``airflow/dags/staging_sources.py``. Shared
PySpark logic lives in ``pipelines/staging_pipeline.py`` and the source
contract lives in ``pipelines/{source}/staging_{source}.json``.

Both layers are Delta tables: each run atomically replaces only its own
``ingest_date`` partition (``replaceWhere``). Reprocessing the same date
only overwrites that partition.

Before doing work, each task checks the partition's processed marker
(written under ``_markers/`` after each Delta commit). If it exists,
the task is skipped instead of reprocessing.
"""


def build_staging_dag(source: str):
    """Create one staging DAG for a registered declarative source."""
    source_config = get_source_config(source)
    staging_asset = Asset(f"staging_{source}")
    raw_base_dir = raw_dir_for(source)
    staging_base_dir = staging_dir_for(source)

    @dag(
        dag_id=source,
        description=source_config["description"],
        schedule=STAGING_SCHEDULE,
        start_date=pendulum.datetime(2024, 1, 1, tz="UTC"),
        catchup=False,
        max_active_runs=1,
        default_args=DEFAULT_ARGS,
        tags=["bigcore", source, "staging"],
        doc_md=_doc_for(source),
    )
    def staging_source_dag():
        @task(task_id="extract_to_raw")
        def extract_to_raw_task(**context) -> dict:
            """Read the source input and write the raw partition."""
            ingest_date = resolve_ingest_date(context)
            log.info("Extract task started for %s - ingest_date=%s", source, ingest_date)

            log.info("Checking raw partition marker at %s", raw_base_dir)
            if delta_partition_processed(raw_base_dir, ingest_date):
                log.info(
                    "Raw for %s already processed (%s) - skipping extraction",
                    ingest_date,
                    raw_base_dir,
                )
                raise AirflowSkipException(f"raw ingest_date={ingest_date} already exists")
            log.info(
                "Raw partition ingest_date=%s not processed yet - extracting", ingest_date
            )

            metrics = run_spark(
                f"{source}_extract", extract_to_raw, source, ingest_date, enable_delta=True
            )
            log.info("Raw layer written for %s: %s", source, metrics)
            return metrics

        @task(
            task_id="transform_to_staging",
            outlets=[staging_asset],
            trigger_rule="none_failed",
        )
        def transform_to_staging_task(**context) -> dict:
            """Read raw, apply the table config and write staging."""
            ingest_date = resolve_ingest_date(context)
            log.info("Transform task started for %s - ingest_date=%s", source, ingest_date)

            log.info("Checking staging partition marker at %s", staging_base_dir)
            if delta_partition_processed(staging_base_dir, ingest_date):
                log.info(
                    "Staging for %s already processed (%s) - skipping transform",
                    ingest_date,
                    staging_base_dir,
                )
                raise AirflowSkipException(f"staging ingest_date={ingest_date} already exists")
            log.info(
                "Staging partition ingest_date=%s not processed yet - transforming", ingest_date
            )

            metrics = run_spark(
                f"{source}_transform",
                transform_to_staging,
                source,
                ingest_date,
                enable_delta=True,
            )
            log.info(
                "Staging layer written for %s: %s records (%s quarantined)",
                source,
                metrics["records_out"],
                metrics["records_quarantined"],
            )
            return metrics

        @task(task_id="data_quality", trigger_rule="none_failed")
        def data_quality_task(**context) -> dict:
            """Log the alert for the partition's quarantined records."""
            ingest_date = resolve_ingest_date(context)
            log.info("Data quality task started for %s - ingest_date=%s", source, ingest_date)

            metrics = run_spark(
                f"{source}_data_quality",
                report_data_quality,
                source,
                ingest_date,
                enable_delta=True,
            )
            log.info(
                "Data quality report for %s: %s of %s record(s) rejected (%s%%)",
                source,
                metrics["records_rejected"],
                metrics["records_total"],
                metrics["rejected_pct"],
            )
            return metrics

        extract_to_raw_task() >> transform_to_staging_task() >> data_quality_task()

    return staging_source_dag()


for source_name in active_sources():
    globals()[source_name] = build_staging_dag(source_name)
